Fetching data for a given patient to the care panel summary
METS-Programme/esm-ugandaemr-core pull request #185
Opened 2024-03-14 00:48 UTC by Daphne210

https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/7ff1bb36-7101-4b0a-a24f-9ef5e6750256

2024-03-15 15:32 UTC, jabahum requested changes

2024-03-15 15:32 UTC, jabahum commented on .vscode/settings.json
> +    "editor.formatOnSave": true,
please remove this

2024-03-15 15:32 UTC, jabahum commented on packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
> +          {switchItem?.name === 'HIV Program' ? (
move this to something like this ```  export const  program = {HIV:"HIV Program"}```

2024-03-15 15:32 UTC, jabahum commented on packages/esm-care-panel-app/src/program-enrollment/program-enrollment.resource.ts
> +  // console.info(JSON.stringify(data, null, 2));
lets remove this unnecessary code

2024-03-15 15:43 UTC, Daphne210 commented on .vscode/settings.json
> +    "editor.formatOnSave": true,
This has been resolved

2024-03-16 07:51 UTC, Daphne210 commented on packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
> +          {switchItem?.name === 'HIV Program' ? (
@jabahum  This has been resolved

2024-03-16 07:51 UTC, Daphne210 commented on packages/esm-care-panel-app/src/program-enrollment/program-enrollment.resource.ts
> +  // console.info(JSON.stringify(data, null, 2));
@jabahum This has been resolved

2024-03-16 11:32 UTC, jabahum commented on packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
> +            <>
we can remove this extract element tag <></>

2024-03-16 13:36 UTC, Mwanje approved these changes

2024-03-16 13:39 UTC, jabahum approved these changes

2024-03-16 13:39 UTC, merged