Add TB app to packages
METS-Programme/esm-ugandaemr-core pull request #73
Opened 2023-08-21 13:23 UTC by Kasulejoseph

2023-08-21 13:32 UTC, Kasulejoseph commented
> @Kasulejoseph let's clean the TB package by removing none tb stuff i.e forms etc

Alright

2023-08-23 04:21 UTC, jabahum requested changes

2023-08-23 04:21 UTC, jabahum commented on packages/esm-tb-app/src/routes.json
> +      "component": "opdDashboardLink",
can we have this changed to the right module names

2023-08-23 04:21 UTC, jabahum commented on packages/esm-tb-app/src/routes.json
> +      "name": "opd-dashboard-ext",
this too

2023-08-23 04:23 UTC, jabahum commented
@Kasulejoseph make sure to run yarn verify to help resolve the CI errors

2023-08-23 08:24 UTC, jabahum approved these changes

2023-08-23 08:24 UTC, jabahum commented on packages/esm-tb-app/translations/en.json
> +{
Do we need opd here

2023-08-23 08:25 UTC, merged